// <auto-generated />
using BenefitsTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BenefitsTracker.Migrations
{
    [DbContext(typeof(BenefitsTrackerContext))]
    [Migration("20181128214639_CostToEmp")]
    partial class CostToEmp
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BenefitsTracker.Data.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmpCost");

                    b.Property<string>("FifthDependent");

                    b.Property<string>("FifthDependentCost");

                    b.Property<string>("FirstDependent");

                    b.Property<string>("FirstDependentCost");

                    b.Property<string>("FourthDependent");

                    b.Property<string>("FourthDependentCost");

                    b.Property<bool>("HasDependents");

                    b.Property<string>("Name");

                    b.Property<string>("SecondDependent");

                    b.Property<string>("SecondDependentCost");

                    b.Property<string>("SixthDependent");

                    b.Property<string>("SixthDependentCost");

                    b.Property<string>("ThirdDependent");

                    b.Property<string>("ThirdDependentCost");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
